#!/usr/bin/env bash
set -euo pipefail

readonly schema='hostwright.phase09.gate07.qualification.manifest.v1'
readonly gate=7 readonly_branch='feat/v0.0.2-phase-09'
readonly live_parent='/Volumes/T9/hostwright/qualification'
readonly signing_fingerprint='A6CFABEC0AA50ABE00A745BAFA83BC24783AA5DB'
readonly signing_identity='Developer ID Application: Dev Trivedi (993YC3JY4Q)'
readonly signing_identifier='dev.hostwright.profile-qualification'
readonly pinned_image='docker.io/library/python@sha256:26730869004e2b9c4b9ad09cab8625e81d256d1ce97e72df5520e806b1709f92'
readonly pinned_image_digest='sha256:26730869004e2b9c4b9ad09cab8625e81d256d1ce97e72df5520e806b1709f92'
readonly state_header=$'gate\tcell\tstatus\tsource_digest\tconfig_digest\ttoolchain_digest\tstarted_at\tfinished_at\tstdout_sha256\tstderr_sha256'
readonly ownership_header=$'recorded_at\ttype\tidentifier\tpath\tdevice\tinode\tidentity'
root='' parent='' source_digest_value='' config_digest_value='' toolchain_digest_value='' source_commit=''
root_lock_created=0 gate_lock_created=0 run_succeeded=0

die(){ printf '%s\n' "$1" >&2; exit "${2:-70}"; }
now(){ /bin/date -u +%Y-%m-%dT%H:%M:%SZ; }
sha(){ /usr/bin/shasum -a 256 "$1" | /usr/bin/awk '{print $1}'; }
stream_sha(){ /usr/bin/shasum -a 256 | /usr/bin/awk '{print $1}'; }
testing(){ [[ "${HOSTWRIGHT_PHASE09_HARNESS_TESTING:-}" == 1 ]]; }

contract(){ cat <<'EOF'
Phase 09 Gate 7 qualification harness contract v1
Gate 7 — 43.75% — secure workload profiles (#202).
Exactly one Gate 7 qualification may be active. Cells 1..6 run strictly serially.
Focused U/I/L/M/S/R evidence covers profile persistence and policy, authenticated daemon,
admission and local-Control integration, a signed profile-bound pinned Apple-container live workload,
schema-v20 migration/reopen/restore, adversarial profile weakening and provider gaps, and
drift/recovery. Failed evidence is immutable; passing evidence is reused cryptographically.
Only ledgered current-user-owned live artifacts are removed after inode/device revalidation.
EOF
}

qualification_parent(){ if testing; then : "${HOSTWRIGHT_PHASE09_HARNESS_TEST_PARENT:?test parent required}"; printf '%s\n' "$HOSTWRIGHT_PHASE09_HARNESS_TEST_PARENT"; else printf '%s\n' "$live_parent"; fi; }
validate_worktree(){ [[ "$(git branch --show-current)" == "$readonly_branch" ]] || die "Gate 7 requires branch $readonly_branch." 66; local top; top="$(/bin/realpath "$(git rev-parse --show-toplevel)")"; [[ "$top" == /Users/dev/Documents/hostwright-phase09 ]] || die 'Gate 7 requires the isolated Phase 09 worktree.' 66; }
validate_root(){ : "${HOSTWRIGHT_PHASE09_GATE_ROOT:?HOSTWRIGHT_PHASE09_GATE_ROOT is required}"; root="$HOSTWRIGHT_PHASE09_GATE_ROOT"; parent="$(qualification_parent)"; local canonical; canonical="$(/bin/realpath "$parent")"; [[ -d "$parent" && ! -L "$parent" && "$canonical" == "$parent" ]] || die 'qualification parent must be canonical and non-symlinked.' 66; if testing; then [[ "$canonical" == /private/var/folders/*/T/hostwright-phase09-harness-* || "$canonical" == /var/folders/*/T/hostwright-phase09-harness-* ]] || die 'test parent must be isolated.' 66; else [[ "$canonical" == "$live_parent" ]] || die 'Gate 7 evidence must use the fixed qualification parent.' 66; fi; [[ "$root" == /* && -d "$root" && ! -L "$root" && "$(/bin/realpath "$root")" == "$root" && "$(/bin/realpath "$(dirname "$root")")" == "$canonical" ]] || die 'evidence root is unsafe.' 66; [[ "${root##*/}" =~ ^phase09-gate07-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$ ]] || die 'evidence root name is not a Gate 7 lowercase UUID.' 66; [[ "$(stat -f '%u' "$root")" == "$(id -u)" && "$(stat -f '%Lp' "$root")" == 700 ]] || die 'evidence root must be current-user-owned and mode 0700.' 66; parent="$canonical"; }
empty_root(){ [[ -z "$(/usr/bin/find "$root" -mindepth 1 -maxdepth 1 -print -quit)" ]] || die 'prepare requires an empty evidence root.' 73; }
source_digest(){ { git rev-parse HEAD; git diff --binary HEAD -- . ':(exclude)tmp'; while IFS= read -r -d '' p; do [[ "$p" == tmp/* || "$p" == .codex/* || "$p" == .claude/* ]] && continue; printf '%s\0' "$p"; /usr/bin/shasum -a 256 "$p"; done < <(git ls-files --others --exclude-standard -z | LC_ALL=C /usr/bin/sort -z); } | stream_sha; }
toolchain(){ { /usr/bin/sw_vers; xcodebuild -version; swift --version; container --version; xcrun --find codesign; security find-identity -p codesigning -v; } 2>&1; }
cell_command(){ case "$1" in
1) printf '%s\n' "swift test --filter 'WorkloadProfileRepositoryTests|WorkloadProfilePolicyEngineTests'";;
2) printf '%s\n' "swift test --filter 'WorkloadProfileControlOperationsTests|PersistentControlAdmissionIntegrationTests|LocalControlProfileIntegrationTests|LifecycleProfileIntegrationTests'";;
3) printf '%s\n' 'signed hostwright-profile-qualification plus one owned pinned Apple-container workload';;
4) printf '%s\n' "swift test --filter 'RBACSchemaV20MigrationTests|WorkloadProfileRepositoryTests/testSchemaV20PersistsWorkloadProfiles|StateUpgradeTests'";;
5) printf '%s\n' "swift test --filter 'WorkloadProfilePolicyEngineTests/(testWeakeningRequiresExactRbacApprovedFutureApproval|testProviderCapabilityDesiredWorkloadAndDriftFailuresAreExplicit)|WorkloadProfileControlOperationsTests/testRBACReadWriteAndWeakeningApprovalAreFailClosed|WorkloadProfileRepositoryTests/(testMissingParentIsRejectedBeforePersistence|testCycleUpdateIsRejectedAndTransactionRollsBack)'";;
6) printf '%s\n' "swift test --filter 'WorkloadProfilePolicyEngineTests/(testProviderCapabilityDesiredWorkloadAndDriftFailuresAreExplicit|testLegacyRequestsWithoutProfileRemainUnbound)|WorkloadProfileRepositoryTests/(testCanonicalCreateListAndReopenRoundTrip|testTamperedCanonicalJSONAndDigestFailClosed)|LifecycleProfileIntegrationTests'; swift build --product hostwrightd; swift build --product hostwright-control; swift build --product hostwright-profile-qualification; scripts/lint.sh; git diff --check; scripts/check-docs.sh";; *) die 'unknown Gate 7 cell.' 70;; esac; }
classes(){ case "$1" in 1) printf '%s\n' '["U"]';;2) printf '%s\n' '["I"]';;3) printf '%s\n' '["L","I"]';;4) printf '%s\n' '["M"]';;5) printf '%s\n' '["S"]';;6) printf '%s\n' '["R","I"]';;*) die 'unknown evidence class.';;esac; }
config_digest(){ { sha "$0"; sha scripts/lint.sh; sha scripts/check-docs.sh; local n; for n in 1 2 3 4 5 6; do cell_command "$n"; classes "$n"; done; } | stream_sha; }
collect(){ source_commit="$(git rev-parse HEAD)"; source_digest_value="$(source_digest)"; config_digest_value="$(config_digest)"; toolchain_digest_value="$(toolchain | stream_sha)"; if ! testing; then [[ -z "$(git status --porcelain --untracked-files=all -- . ':(exclude)tmp')" ]] || die 'Gate 7 qualification requires a clean committed branch.' 73; fi; }
cells_json(){ local n; for n in 1 2 3 4 5 6; do /usr/bin/jq -n --argjson cell "$n" --arg command "$(cell_command "$n")" --argjson evidenceClasses "$(classes "$n")" '{cell:$cell,command:$command,evidenceClasses:$evidenceClasses}'; done | /usr/bin/jq -s .; }
prepare(){ printf '%s\n' "$ownership_header" > "$root/ownership-v1.tsv"; printf '%s\n' "$state_header" > "$root/state-v1.tsv"; toolchain > "$root/toolchain-v1.txt"; /usr/bin/jq -n --arg schema "$schema" --argjson gate "$gate" --arg sourceCommit "$source_commit" --arg sourceDigest "$source_digest_value" --arg configDigest "$config_digest_value" --arg toolchainDigest "$toolchain_digest_value" --arg startedAt "$(now)" --argjson evidenceByCell "$(cells_json)" '{schema:$schema,gate:$gate,sourceCommit:$sourceCommit,sourceDigest:$sourceDigest,configDigest:$configDigest,toolchainDigest:$toolchainDigest,cellOrder:[1,2,3,4,5,6],evidenceByCell:$evidenceByCell,startedAt:$startedAt,completedAt:null,status:"prepared"}' > "$root/manifest-v1.json"; chmod 600 "$root"/*; }
prepared(){ local f; for f in manifest-v1.json ownership-v1.tsv state-v1.tsv toolchain-v1.txt; do [[ -f "$root/$f" && ! -L "$root/$f" ]] || die 'run requires a complete prepared evidence root.' 73; done; [[ "$(head -n 1 "$root/ownership-v1.tsv")" == "$ownership_header" && "$(head -n 1 "$root/state-v1.tsv")" == "$state_header" ]] || die 'prepared evidence headers are invalid.' 73; [[ "$(/usr/bin/jq -r .schema "$root/manifest-v1.json")" == "$schema" && "$(/usr/bin/jq -r .gate "$root/manifest-v1.json")" == 7 && "$(/usr/bin/jq -r .sourceDigest "$root/manifest-v1.json")" == "$source_digest_value" && "$(/usr/bin/jq -r .configDigest "$root/manifest-v1.json")" == "$config_digest_value" && "$(/usr/bin/jq -r .toolchainDigest "$root/manifest-v1.json")" == "$toolchain_digest_value" ]] || die 'prepared evidence dependencies changed; preserve this root.' 73; }
record_root(){ local runtime="$1"; [[ "$runtime" == "$root/live-runtime-v1" && -d "$runtime" && ! -L "$runtime" && "$(/bin/realpath "$runtime")" == "$runtime" && "$(stat -f '%u' "$runtime")" == "$(id -u)" && "$(stat -f '%Lp' "$runtime")" == 700 ]] || die 'live runtime root is unsafe.'; printf '%s\ttemporary-root\tgate07-live-runtime\t%s\t%s\t%s\tpath=live-runtime-v1;scope=gate07-live\n' "$(now)" "$runtime" "$(stat -f '%d' "$runtime")" "$(stat -f '%i' "$runtime")" >> "$root/ownership-v1.tsv"; }
record_file(){ local runtime="$1" p="$2" n="${2##*/}"; [[ "$(dirname "$p")" == "$runtime" && -f "$p" && ! -L "$p" && "$(/bin/realpath "$p")" == "$p" && "$(stat -f '%u' "$p")" == "$(id -u)" ]] || die 'live artifact is not owned.'; case "$n" in signed-profile-tool|state.sqlite|state.sqlite-wal|state.sqlite-shm) ;; *) [[ "$n" =~ ^\.hostwright-[a-f0-9]{16}-access-v1\.lock(\.writer)?$ ]] || die 'live runtime contains an unowned file.';; esac; printf '%s\ttemporary-file\t%s\t%s\t%s\t%s\tname=%s;scope=gate07-live\n' "$(now)" "$n" "$p" "$(stat -f '%d' "$p")" "$(stat -f '%i' "$p")" "$n" >> "$root/ownership-v1.tsv"; }
inventory(){ local runtime="$1" p count=0; while IFS= read -r -d '' p; do /usr/bin/awk -F $'\t' -v p="$p" '$2=="temporary-file"&&$4==p{n++}END{exit(n==0?1:n==1?0:2)}' "$root/ownership-v1.tsv" || { [[ "$?" == 1 ]] && record_file "$runtime" "$p" || die 'live artifact has duplicate ledger records.'; }; count=$((count+1)); done < <(/usr/bin/find "$runtime" -mindepth 1 -maxdepth 1 -type f -print0); [[ "$count" -ge 2 && -f "$runtime/signed-profile-tool" && -f "$runtime/state.sqlite" ]] || die 'live inventory is incomplete.'; [[ -z "$(/usr/bin/find "$runtime" -mindepth 1 -maxdepth 1 ! -type f -print -quit)" ]] || die 'live runtime contains a non-file child.'; }
cleanup_live(){ local runtime="$1" line path d i root_path root_device root_inode; line="$(/usr/bin/awk -F $'\t' '$2=="temporary-root"&&$3=="gate07-live-runtime"{print $4"\t"$5"\t"$6}' "$root/ownership-v1.tsv")"; [[ -n "$line" && "$line" != *$'\n'* ]] || die 'live root ledger entry is missing or duplicated.'; IFS=$'\t' read -r root_path root_device root_inode <<< "$line"; [[ "$root_path" == "$runtime" && -d "$runtime" && ! -L "$runtime" && "$(/bin/realpath "$runtime")" == "$runtime" && "$(stat -f '%d' "$runtime")" == "$root_device" && "$(stat -f '%i' "$runtime")" == "$root_inode" ]] || die 'live root identity changed; cleanup is refused.'; while IFS=$'\t' read -r path d i; do [[ "$(dirname "$path")" == "$runtime" && -f "$path" && ! -L "$path" && "$(/bin/realpath "$path")" == "$path" && "$(stat -f '%d' "$path")" == "$d" && "$(stat -f '%i' "$path")" == "$i" ]] || die 'live artifact identity changed; cleanup is refused.'; /bin/unlink "$path"; done < <(/usr/bin/awk -F $'\t' '$2=="temporary-file"{print $4"\t"$5"\t"$6}' "$root/ownership-v1.tsv"); [[ -z "$(/usr/bin/find "$runtime" -mindepth 1 -maxdepth 1 -print -quit)" ]] || die 'live root is not empty after owned-only cleanup.'; /bin/rmdir "$runtime"; }
record_container(){ local resource="$1"; [[ "$resource" =~ ^hostwright-p09-g07-[a-f0-9]{16}$ ]] || die 'Gate 7 live container identifier is unsafe.'; printf '%s\tcontainer-resource\t%s\t\t\t\timage=%s;scope=gate07-live\n' "$(now)" "$resource" "$pinned_image_digest" >> "$root/ownership-v1.tsv"; }
live(){ swift build --product hostwright-profile-qualification; local bin tool runtime signed result status team canonical resource output latest_schema; bin="$(swift build --show-bin-path)"; tool="$bin/hostwright-profile-qualification"; [[ -x "$tool" ]] || die 'Gate 7 profile qualification product was not built.'; latest_schema="$(/usr/bin/awk '/stateSchema = /{print $NF; exit}' Sources/HostwrightCore/ContractVersions.swift)"; [[ "$latest_schema" =~ ^[0-9]+$ ]] || die 'could not determine the latest Gate 7 state schema version.' 69; runtime="$root/live-runtime-v1"; mkdir "$runtime"; chmod 700 "$runtime"; record_root "$runtime"; signed="$runtime/signed-profile-tool"; /bin/cp "$tool" "$signed"; codesign --force --sign "$signing_fingerprint" --identifier "$signing_identifier" "$signed"; codesign --verify --strict "$signed"; team="$(codesign -d --verbose=4 "$signed" 2>&1|/usr/bin/awk -F= '$1=="TeamIdentifier"{print $2}')"; [[ "$team" == 993YC3JY4Q ]] || die 'signed live tool has the wrong team.'; record_file "$runtime" "$signed"; set +e; result="$("$signed" --root "$runtime" --probe-apple-container)"; status=$?; set -e; inventory "$runtime"; [[ "$status" == 0 && -n "$result" && "${#result}" -le 1048576 ]] || die 'profile live qualification failed.' "$status"; canonical="$(printf '%s' "$result"|/usr/bin/jq -cS .)"; [[ "$canonical" == "$result" ]] || die 'live result is not canonical JSON.'; printf '%s' "$result"|/usr/bin/jq -e --argjson latest "$latest_schema" '.kind=="hostwright.phase09.profile.qualification.v1" and .stateSchemaVersion==$latest and .integrityHealth=="healthy" and .appleContainerCapabilityProbed==true and .supportedProfileAllowed==true and .liveWorkloadValidated==true and .unsupportedProfileDenied==true and .admissionBound==true and .persistedAcrossReopen==true' >/dev/null; container image list --format json | /usr/bin/jq -e --arg image "$pinned_image" --arg digest "$pinned_image_digest" 'any(.[]; .configuration.name==$image and .configuration.descriptor.digest==$digest)' >/dev/null || die 'the exact pinned Gate 7 image is not local; no pull is permitted.' 69; resource="hostwright-p09-g07-$(printf '%s' "$root"|stream_sha|cut -c1-16)"; container list --all --format json | /usr/bin/jq -e --arg id "$resource" 'all(.[]; .id!=$id)' >/dev/null || die 'the owned Gate 7 container identifier already exists.' 73; record_container "$resource"; set +e; output="$(container run --rm --name "$resource" --read-only --cpus 1 --memory 256M --no-dns "$pinned_image" /bin/sh -c 'printf hostwright-profile-live')"; status=$?; set -e; [[ "$status" == 0 && "$output" == hostwright-profile-live ]] || die 'the profile-bound pinned Apple-container workload failed.' "$status"; container list --all --format json | /usr/bin/jq -e --arg id "$resource" 'all(.[]; .id!=$id)' >/dev/null || die 'the owned Gate 7 container was not removed.'; printf '%s\n' "$result"; cleanup_live "$runtime"; }
run_cell(){ case "$1" in 1) swift test --filter 'WorkloadProfileRepositoryTests|WorkloadProfilePolicyEngineTests';;2) swift test --filter 'WorkloadProfileControlOperationsTests|PersistentControlAdmissionIntegrationTests|LocalControlProfileIntegrationTests|LifecycleProfileIntegrationTests';;3) live;;4) swift test --filter 'RBACSchemaV20MigrationTests|WorkloadProfileRepositoryTests/testSchemaV20PersistsWorkloadProfiles|StateUpgradeTests';;5) swift test --filter 'WorkloadProfilePolicyEngineTests/(testWeakeningRequiresExactRbacApprovedFutureApproval|testProviderCapabilityDesiredWorkloadAndDriftFailuresAreExplicit)|WorkloadProfileControlOperationsTests/testRBACReadWriteAndWeakeningApprovalAreFailClosed|WorkloadProfileRepositoryTests/(testMissingParentIsRejectedBeforePersistence|testCycleUpdateIsRejectedAndTransactionRollsBack)';;6) swift test --filter 'WorkloadProfilePolicyEngineTests/(testProviderCapabilityDesiredWorkloadAndDriftFailuresAreExplicit|testLegacyRequestsWithoutProfileRemainUnbound)|WorkloadProfileRepositoryTests/(testCanonicalCreateListAndReopenRoundTrip|testTamperedCanonicalJSONAndDigestFailClosed)|LifecycleProfileIntegrationTests'; swift build --product hostwrightd; swift build --product hostwright-control; swift build --product hostwright-profile-qualification; scripts/lint.sh; git diff --check; scripts/check-docs.sh;;*) die 'unknown Gate 7 cell.';;esac; }
state(){ printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$gate" "$1" "$2" "$source_digest_value" "$config_digest_value" "$toolchain_digest_value" "$3" "$4" "$5" "$6" >> "$root/state-v1.tsv"; chmod 600 "$root/state-v1.tsv"; }
failure(){ [[ -f "$root/failure-v1.tsv" ]] || printf '%s\n' $'recorded_at\tgate\tcell\texit_status\tcommand\tstdout_sha256\tstderr_sha256' > "$root/failure-v1.tsv"; printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$(now)" "$gate" "$1" "$2" "$3" "$4" "$5" >> "$root/failure-v1.tsv"; chmod 600 "$root/failure-v1.tsv"; }
manifest(){ local tmp="$root/.manifest.tmp"; /usr/bin/jq --arg s "$1" --arg t "$2" '.status=$s|.completedAt=(if $t==""then null else $t end)' "$root/manifest-v1.json">"$tmp"; chmod 600 "$tmp"; /bin/mv "$tmp" "$root/manifest-v1.json"; }
reusable(){ local n o e os es; for n in 1 2 3 4 5 6; do /usr/bin/awk -F $'\t' -v n="$n" -v s="$source_digest_value" -v c="$config_digest_value" -v t="$toolchain_digest_value" '$1==7&&$2==n&&$3=="pass"&&$4==s&&$5==c&&$6==t{f=1}END{exit f?0:1}' "$root/state-v1.tsv" || return 1; o="$root/cell-$(printf '%02d' "$n").stdout.log"; e="$root/cell-$(printf '%02d' "$n").stderr.log"; [[ -f "$o" && -f "$e" ]] || return 1; os="$(/usr/bin/awk -F $'\t' -v n="$n" '$1==7&&$2==n&&$3=="pass"{x=$9}END{print x}' "$root/state-v1.tsv")"; es="$(/usr/bin/awk -F $'\t' -v n="$n" '$1==7&&$2==n&&$3=="pass"{x=$10}END{print x}' "$root/state-v1.tsv")"; [[ "$(sha "$o")" == "$os" && "$(sha "$e")" == "$es" ]] || return 1; done; }
verify(){ local tmp status=0 count; [[ -f "$root/evidence-v1.sha256" && ! -L "$root/evidence-v1.sha256" && -f "$root/evidence-v1.cms" && ! -L "$root/evidence-v1.cms" ]] || return 1; count="$(/usr/bin/wc -l < "$root/evidence-v1.sha256"|tr -d ' ')"; [[ "$count" == 17 ]] || return 1; /usr/bin/awk 'NF!=2||$1!~/^[a-f0-9]{64}$/||$2!~/^(manifest-v1\.json|state-v1\.tsv|ownership-v1\.tsv|toolchain-v1\.txt|gate-active-run-v1-info\.tsv|cell-[0-9][0-9]\.(stdout|stderr)\.log)$/||seen[$2]++{exit 1}END{exit NR==17?0:1}' "$root/evidence-v1.sha256" || return 1; tmp="$(/usr/bin/mktemp /tmp/hostwright-phase09-gate07-evidence.XXXXXX)" || return 1; security cms -D -u 9 -i "$root/evidence-v1.cms" -o "$tmp" >/dev/null 2>&1 || status=1; /usr/bin/cmp -s "$root/evidence-v1.sha256" "$tmp" || status=1; (cd "$root"&&/usr/bin/shasum -a 256 -c evidence-v1.sha256 >/dev/null) || status=1; /bin/unlink "$tmp"; [[ "$status" == 0 ]]; }
release(){ if [[ "$run_succeeded" == 1 && "$root_lock_created" == 1 && "$gate_lock_created" == 1 ]]; then /bin/rmdir "$root/active-run-v1"; /bin/rmdir "$parent/.phase09-gate07-active-v1"; root_lock_created=0; gate_lock_created=0; fi; }
write_digest(){ (cd "$root"; for f in manifest-v1.json state-v1.tsv ownership-v1.tsv toolchain-v1.txt gate-active-run-v1-info.tsv cell-*.stdout.log cell-*.stderr.log; do [[ -f "$f" ]]&&/usr/bin/shasum -a 256 "$f"; done|LC_ALL=C sort)>"$root/evidence-v1.sha256"; chmod 600 "$root/evidence-v1.sha256"; security cms -S -N "$signing_identity" -H SHA256 -u 9 -i "$root/evidence-v1.sha256" -o "$root/evidence-v1.cms"; chmod 600 "$root/evidence-v1.cms"; }
run(){ prepared; if [[ -e "$root/evidence-v1.sha256" || -e "$root/evidence-v1.cms" ]]; then [[ "$(/usr/bin/jq -r .status "$root/manifest-v1.json")" == passed ]]&&reusable&&verify || die 'completed evidence is incomplete or changed; preserve this root and do not rerun.' 73; printf '%s\n' 'Gate 7 evidence is valid and reused; no cells were rerun.'; return; fi; local lock="$parent/.phase09-gate07-active-v1" n cmd out err start end status; [[ ! -e "$root/active-run-v1" && ! -e "$lock" ]] || die 'An active Gate 7 qualification already exists; do not duplicate it.' 75; mkdir "$lock"; chmod 700 "$lock"; printf '%s\n' $'root\tpid\tstarted_at\tsource_digest\tconfig_digest\ttoolchain_digest'>"$lock/info-v1.tsv"; printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$root" "$$" "$(now)" "$source_digest_value" "$config_digest_value" "$toolchain_digest_value">>"$lock/info-v1.tsv"; chmod 600 "$lock/info-v1.tsv"; gate_lock_created=1; mkdir "$root/active-run-v1"; chmod 700 "$root/active-run-v1"; root_lock_created=1; trap release EXIT; for n in 1 2 3 4 5 6; do cmd="$(cell_command "$n")"; out="$root/cell-$(printf '%02d' "$n").stdout.log"; err="$root/cell-$(printf '%02d' "$n").stderr.log"; [[ ! -e "$out" && ! -e "$err" ]]||die 'Cell logs already exist; preserve this root and do not rerun.' 73; start="$(now)"; set +e; (set -e;run_cell "$n")>"$out" 2>"$err"; status=$?; set -e; chmod 600 "$out" "$err"; end="$(now)"; if [[ "$status" != 0 ]]; then state "$n" failed "$start" "$end" "$(sha "$out")" "$(sha "$err")"; failure "$n" "$status" "$cmd" "$(sha "$out")" "$(sha "$err")"; manifest failed "$end"; die "Gate 7 cell $n failed; progress is frozen and locks are preserved." "$status"; fi; state "$n" pass "$start" "$end" "$(sha "$out")" "$(sha "$err")"; done; manifest passed "$(now)"; /bin/cp "$lock/info-v1.tsv" "$root/gate-active-run-v1-info.tsv"; chmod 600 "$root/gate-active-run-v1-info.tsv"; write_digest; /bin/unlink "$lock/info-v1.tsv"; run_succeeded=1; release; printf '%s\n' 'Gate 7 qualification passed.'; }
main(){ [[ "$#" -ge 1 ]]||die 'usage: phase09-gate07-qualification.sh <contract|prepare|run>.' 64; case "$1" in contract) [[ "$#" == 1 ]]||die 'contract accepts no arguments.' 64;contract;;prepare) [[ "$#" == 2 && "$2" == 7 ]]||die 'Gate 7 harness accepts only prepare 7.' 64;validate_worktree;validate_root;empty_root;collect;prepare;printf '%s\n' 'Gate 7 evidence root prepared.';;run) [[ "$#" == 2 && "$2" == 7 ]]||die 'Gate 7 harness accepts only run 7.' 64;validate_worktree;validate_root;collect;run;;*) die 'unknown qualification command.' 64;;esac; }
main "$@"
